### PR TITLE
G7 pull request

### PR DESCRIPTION
**Pull request by JoanWu5**
Group 7 chemotaxis codes, I don't know what conflicts with the master, we are fine last night till lots of groups request-pull today

### CODE REVIEW

**Comment by griff4692** [comment]
Hi - can you make sure to only include changes to your g7 directories (in src and maps)?

**Comment by JoanWu5** [comment]
> Hi - can you make sure to only include changes to your g7 directories (in src and maps)?

Okay， I see the conflict file ars src/.DS_Store and src/chemotaxis/.DS_Store, actually I don't see them in our group codes

**Comment by JoanWu5** [comment]
> Hi - can you make sure to only include changes to your g7 directories (in src and maps)?

could you please ignore these two files? and I think we don't need

**Comment by JoanWu5** [comment]
Okay, I have done, now you can merge

**Pull request closed without merging**
