### PR TITLE
2021-09-22 G1 progress

### PR DESCRIPTION
**Pull request by emesterhazy**

### CODE REVIEW

**Comment by thenamangoyal** [comment]
You have inadvertently removed this file from `src/chemotaxis/g9/Agent.java` belonging to G9.

**Comment by emesterhazy** [comment]
@thenamangoyal  Should be fixed now. We had to remove that file when we were working because it had a compilation error, but I thought I merged it back in when I opened the PR. It would be ideal for future projects if the class could keep two branches on the main repo:

1. A main simulator branch that contains *no* student code, only the simulator code and any subsequent updates to it. If there are updates to the simulator after students start working on the project, they would be pushed to this branch and merged into the branch below.
2. A branch that accepts student pull requests for class demos. Any changes to the simulator code would be merged into here as well.

I think this setup would allow teams to pull updates to the simulator code into their repos without also pulling in code from other groups (which might not compile). Come to think of it, I guess this will be less of an issue if the remaining projects use python, but I still think this would be a best practice so that the change history for the simulator code is easily visible.

**Comment by griff4692** [comment]
Please remove folders in non-group specific directories

**Comment by emesterhazy** [comment]
@griff4692 Sorry, can you clarify which folder(s) you're referring to? I'm not aware that we added any but I must be missing something.

**Comment by thenamangoyal** [comment]
Please remove changes to gitignore and Makefile

**Comment by emesterhazy** [comment]
@griff4692 @thenamangoyal Ok, those changes have been reverted.

**Pull request merged**
