### PR TITLE
g7

### PR DESCRIPTION
**Pull request by ForLittleBeauty**

### CODE REVIEW

**Comment by griff4692** [comment]
Hi - please remove the .DS_Store files and then I will merge

**Comment by ForLittleBeauty** [comment]
Hi Griffin, I have moved all the DS files, can you see them now? Thank you very much.

**Comment by thenamangoyal** [comment]
@ForLittleBeauty  Could also remove the .DS_Store in the root directory of the repo, it's causing merge conflicts

**Comment by ForLittleBeauty** [comment]
Sorry, thank you for you patient, finished !

**Pull request merged**
